[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
  \.git
 | \.venv
 | build
 | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["core_utils", "detector", "pose", "scripts", "tracker"]
skip = ["venv", "yolov5"]

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",  # whitespace before ':' (conflicts with black)
    "W503"   # line break before binary operator (prefer line break after)
]
exclude = [
  ".git",
  "venv",
  "yolov5",
  "__pycache__",
  "build",
  "dist"
]